language: node_js

node_js:
  - "12"

branches:
  only:
  - master
  - staging

notifications:
  email: false

install:
  - echo $SFTP_KNOWN_HOST >> $HOME/.ssh/known_hosts
  - npm i

script:
  - npm run lint
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy-staging.sh
    on:
      branch: staging