language: node_js

node_js:
  - "12"

branches:
  only:
  - master

notifications:
  email: false

install:
  - echo $SFTP_KNOWN_HOST >> $HOME/.ssh/known_hosts
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
