language: php

php:
  - 7.2

branches:
  only:
  - master

notifications:
  email: false

install:
  - echo $SFTP_KNOWN_HOST >> $HOME/.ssh/known_hosts

script:
  - echo "skipping tests"

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master