language: php

php:
  - 7.2

git:
  depth: 1

branches:
  only:
  - master

install:
  - echo $SFTP_KNOWN_HOST >> $HOME/.ssh/known_hosts

script:
  - echo "skipping tests"

after_success:
  - echo "${SFTP_KEY}" | base64 --decode > /tmp/beejee.pem

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master